name: oslo_bysykkel_env
dependencies:
  - python=3.6
  - pandas=0.23.4
  - simplejson=3.16.0
  - requests=2.19.1
  - pytest=4.0.0
  - flask
  - flask-sqlalchemy
  - pip
  - pip:
    - flask-restful==0.3.6